### ISSUE TITLE
Scroll ned er langsomt 

### ISSUE THREAD

**Issue by whitewillow** [whitewillow/dkfds-vue3#12]
Scroll ned er langsomt, clunky - om ikke andet i chrome.
Se evt. hvad DR.dk har gjort.

**Comment by rickirunge** [comment]
Der er ingen problemer på mac.

Men syntes det er lidt bekymrene hvis css kan få browser til at reagere langsomt - så må der da være et eller andet helt gal med den css

**Comment by whitewillow** [comment]
Det viser sig at:

`scroll-behavior: smooth;`

Ihvertfald for Chrome browser gør scrolling langsom
