### ISSUE TITLE
Accordion - invalid disabled-attribute på wrapper-div

### ISSUE THREAD

**Issue by rickirunge** [whitewillow/dkfds-vue3#50]
Ifølge HTML spec kan disabled kun sættes på form-controls, hvilket DIV jo ikke er.

Kan heller ikke lige gennemskue hvorfor der er disabled på den, og hvad det skulle gøre?
Er det fordi man gerne ville gøre det muligt disabled muligheden for at folde ud/ind?

**Comment by whitewillow** [comment]
God pointe - disabled skal fjernet på denne

**Comment by rickirunge** [comment]
Eller også skal den være på component, men skal resultere i at accordion ikke kan foldes ud/ind, altså at button-ting bliver fjernet fra div, eller på anden måde gjort så der ikke sker noget hvis man forsøger at aktivere fold ud/ind. Og på en måde så det også giver mening for keyboard-navigation og skærmlæser, hvorfor man ikke kan det.

**Comment by whitewillow** [comment]
PT er disabled fjernet - FDS og diverse aria guidelines gør ikke brug af disabled på accordians - dertil siger de heller ikke at man ikke kan. Men indtil et ønske opstår, så er denne fjernet.
Opret gerne issue på at det skal være muligt at disable denne
