### ISSUE TITLE
Accordion: Mulighed for at have heading-tag som overskrift

### ISSUE THREAD

**Issue by rickirunge** [whitewillow/dkfds-vue3#51]
DKFDS giver mulighed for at have heading-tag som overskrift (H1-6) men den mulighed har man ikke her.

**Comment by whitewillow** [comment]
Det er muligt at benytte template #header

Måske det samme, som forslaget til cards (https://github.com/whitewillow/dkfds-vue3/issues/53)

```
h: {
    type: Number,
    default: 2,
},
```

**Comment by whitewillow** [comment]
Se https://github.com/whitewillow/dkfds-vue3/issues/62
