### ISSUE TITLE
Beskeder: Mangler aria-role

### ISSUE THREAD

**Issue by rickirunge** [whitewillow/dkfds-vue3#52]
DKDFS beskriver at en besked skal have `role=alert` så oplæser også bemærker at beskeden dukkede op på skærmen

**Comment by whitewillow** [comment]
PÅ https://designsystem.dk/kode/komponenter/beskeder/
Nævner de kun ved `warning` og `error`.
Dertil https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role anbefaler lign.
Jeg sætter rolle og atomic ved `warning` og `error`
