### ISSUE TITLE
Card: Man er låst til at det skal være H2-header

### ISSUE THREAD

**Issue by rickirunge** [whitewillow/dkfds-vue3#53]
Syntes det begrænser bruges noget at man er låst til at at header i card altid bliver H2.
Hvis nu hvis man er nået til H3 i niveau?

**Comment by whitewillow** [comment]
Det er muligt at benytte `template #header`

Dertil forslag (gælder også Accordian https://github.com/whitewillow/dkfds-vue3/issues/51):

```
h: {
    type: Number,
    default: 2,
},
```
Det bliver til:

```
 <fds-card
  header="Overskrift"
  h="2"
  subheader="Understøttende tekst">...
</fds-card>
```

**Comment by whitewillow** [comment]
Eller helt fjerne header, således og så er det op til bruger at smide det direkte i slot:

```
<fds-card>
  <h2>Overskrift</h2>
  <p>
    In sollicitudin, nulla sit amet facilisis euismod, ex ex hendrerit eros, et egestas
    purus lectus vitae tortor.
  </p>
</fds-card>
```

Dette vil blive oversat til:
```

<div class="card">
  <div class="card-text">
     <h2>Overskrift</h2>
    <p>
    In sollicitudin, nulla sit amet facilisis euismod, ex ex hendrerit eros, et egestas
    purus lectus vitae tortor.
  </p>
  </div>
</div>
```

**Eller måske omskrive cards lidt - design system har** 
PT:
.card-content - ingen padding bruge evt til grafer
.card-footer .card-action - bunden af card til actions
.card-text - bruges til tekst og har padding

hvorfor ikke fjerne .card-text og have header og tekst sammen her

Så bliver det mere rent:

```
<div class="card">
   <div class="card-content">...</div>
   <h2>Overskrift</h2>
   <p>
    In sollicitudin, nulla sit amet facilisis euismod, ex ex hendrerit eros, et egestas
    purus lectus vitae tortor.
   </p>
   <div class="card-footer card-action">...</div>
</div>
```


https://designsystem.dk/kode/komponenter/cards/

**Comment by whitewillow** [comment]
Se https://github.com/whitewillow/dkfds-vue3/issues/62

**Comment by whitewillow** [comment]
På lige fod med fds-accordian får `fds-card`
`header-tag`.
