### ISSUE TITLE
xfds-trinindikator - fanger ikke skift

### ISSUE THREAD

**Issue by kennethrorstromnine** [whitewillow/dkfds-vue3#74]
mounted skal laves om til watch/computed get/set

Overvej om fds-trinindikator size ikke også skal med.
Måske dette skal laves om fra size til noget alla "responsive" (overflow-menu--lg-no-responsive)

**Comment by whitewillow** [comment]
Trin er nu altid default large - dette giver standard responsive funktionalitet
